# Generated by Django 4.2.7 on 2025-08-16 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklySurveillanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=100)),
                ('week_number', models.IntegerField()),
                ('year', models.IntegerField(default=2024)),
                ('previous_week_cases', models.IntegerField(blank=True, null=True)),
                ('current_week_cases', models.IntegerField(blank=True, null=True)),
                ('change_in_cases', models.IntegerField(blank=True, null=True)),
                ('same_week_last_year', models.IntegerField(blank=True, null=True)),
                ('year_over_year_change', models.IntegerField(blank=True, null=True)),
                ('trend', models.CharField(blank=True, max_length=200, null=True)),
                ('top_affected_districts', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveillance_data', to='surveillance.disease')),
            ],
            options={
                'ordering': ['-week_number', 'disease__name'],
                'unique_together': {('week_number', 'year', 'disease')},
            },
        ),
        migrations.CreateModel(
            name='DistrictCaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_data', to='surveillance.district')),
                ('surveillance_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_cases', to='surveillance.weeklysurveillancedata')),
            ],
            options={
                'ordering': ['-cases'],
                'unique_together': {('surveillance_data', 'district')},
            },
        ),
    ]
